# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=20)),
                ('temperature_type', models.CharField(max_length=1, unique=True)),
                ('zipcode', models.CharField(max_length=5, unique=True)),
                ('date_measured', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
