# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_weather_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='date_measured',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='weather',
            name='last_measured',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
