# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20170902_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temperature_type',
            field=models.CharField(max_length=1),
        ),
    ]
